# Logistic Regression

In [25]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [26]:
dataset = pd.read_csv('heart.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [27]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [28]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [29]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=0, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

## Confusion Matrix and Accuracy Score for Logistic Regression


In [30]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[24  9]
 [ 4 39]]


0.8289473684210527

# Decision Tree Classification

In [31]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [32]:
dataset = pd.read_csv('heart.csv')
A = dataset.iloc[:, :-1].values
b = dataset.iloc[:, -1].values

In [33]:
from sklearn.model_selection import train_test_split
A_train, A_test, b_train, b_test = train_test_split(A, b, test_size = 0.25, random_state = 0)

In [34]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
A_train = sc.fit_transform(A_train)
A_test = sc.transform(A_test)

In [35]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifier.fit(A_train, b_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='entropy',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=0, splitter='best')

## Confusion Matrix and Accuracy Score for Decision Tree Classification


In [36]:
from sklearn.metrics import confusion_matrix, accuracy_score
b_pred = classifier.predict(A_test)
cm = confusion_matrix(b_test, b_pred)
print(cm)
accuracy_score(b_test, b_pred)

[[24  9]
 [ 6 37]]


0.8026315789473685

# Random Forest Classification

In [37]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [38]:
dataset = pd.read_csv('heart.csv')
I = dataset.iloc[:, :-1].values
j = dataset.iloc[:, -1].values

In [39]:
from sklearn.model_selection import train_test_split
I_train, I_test, j_train, j_test = train_test_split(I, j, test_size = 0.25, random_state = 0)

In [40]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
I_train = sc.fit_transform(I_train)
I_test = sc.transform(I_test)

In [41]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
classifier.fit(I_train, j_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='entropy', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

## Confusion Matrix and Accuracy Score for Random Forest Classification


In [42]:
from sklearn.metrics import confusion_matrix, accuracy_score
j_pred = classifier.predict(I_test)
cm = confusion_matrix(j_test, j_pred)
print(cm)
accuracy_score(j_test, j_pred)

[[24  9]
 [ 4 39]]


0.8289473684210527